'use server';

/**
 * @fileOverview This file defines a Genkit flow for suggesting relevant remarks based on test results.
 *
 * The flow takes test results as input and returns suggested remarks generated by an AI model.
 * It exports:
 *   - `suggestRelevantRemarks`: An async function that takes TestResultsInput and returns a Promise of SuggestedRemarksOutput.
 *   - `TestResultsInput`: The TypeScript type definition for the input schema.
 *   - `SuggestedRemarksOutput`: The TypeScript type definition for the output schema.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const TestResultsInputSchema = z.object({
  testName: z.string().describe('The name of the test performed.'),
  testResults: z.record(z.string(), z.number()).describe('A map of test parameters to their numerical results.'),
  referenceRanges: z.record(z.string(), z.object({min: z.number(), max: z.number()})).optional().describe('Reference ranges for each test parameter.'),
  statisticalData: z.string().optional().describe('Statistical data related to the test and patient population.'),
  predefinedRules: z.string().optional().describe('Predefined rules for generating remarks based on test results.'),
});
export type TestResultsInput = z.infer<typeof TestResultsInputSchema>;

const SuggestedRemarksOutputSchema = z.object({
  remarks: z.array(z.string()).describe('An array of suggested remarks based on the test results.'),
});
export type SuggestedRemarksOutput = z.infer<typeof SuggestedRemarksOutputSchema>;

export async function suggestRelevantRemarks(input: TestResultsInput): Promise<SuggestedRemarksOutput> {
  return suggestRelevantRemarksFlow(input);
}

const suggestRelevantRemarksPrompt = ai.definePrompt({
  name: 'suggestRelevantRemarksPrompt',
  input: {schema: TestResultsInputSchema},
  output: {schema: SuggestedRemarksOutputSchema},
  prompt: `You are an AI assistant that analyzes lab test results and suggests relevant remarks for lab technicians.

  Analyze the following test results for the test "{{testName}}":

  Results: {{#each testResults}}{{{@key}}}: {{{this}}}
  {{/each}}

  {{#if referenceRanges}}
  Reference Ranges:
  {{#each referenceRanges}}
    {{@key}}: min={{{this.min}}}, max={{{this.max}}}
  {{/each}}
  {{/if}}

  {{#if statisticalData}}
  Statistical Data: {{{statisticalData}}}
  {{/if}}

  {{#if predefinedRules}}
  Predefined Rules: {{{predefinedRules}}}
  {{/if}}

  Based on the test results, reference ranges (if provided), statistical data (if provided), and predefined rules (if provided), suggest relevant remarks that a lab technician can use. Return the remarks in an array of strings.
  `,
});

const suggestRelevantRemarksFlow = ai.defineFlow(
  {
    name: 'suggestRelevantRemarksFlow',
    inputSchema: TestResultsInputSchema,
    outputSchema: SuggestedRemarksOutputSchema,
  },
  async input => {
    const {output} = await suggestRelevantRemarksPrompt(input);
    return output!;
  }
);
